"""Polls the e2e Gatus instance and checks the endpoints generated by pangolin-gatus-sync."""

import json
import sys
import time
from urllib.error import URLError
from urllib.request import urlopen

GATUS = "http://localhost:18080/api/v1/endpoints/statuses"
EXPECTED = {
    # name: (group, expected success of the last result)
    "Pangolin API": ("Pangolin", True),
    "Nextcloud": ("Produzione", True),    # label env:prod
    "Grafana": ("Squadre", False),        # health == unhealthy; labels env:prod + team:infra, team:* is listed first
    "Starting up": ("Staging", True),     # health == unknown with an active check (FAIL_ON_UNKNOWN=false)
    "Cost $avings": ("Pangolin", True),   # no label: default group; $ escaped as $$ in the file
}
ABSENT = {"No health check", "Disabled"}


def statuses():
    with urlopen(GATUS, timeout=5) as response:
        return json.load(response)


def main():
    deadline = time.time() + 120
    last_error = "no answer yet"
    while time.time() < deadline:
        try:
            current = {s["name"]: s for s in statuses() if s.get("results")}
        except (URLError, OSError, ValueError) as exc:
            last_error = str(exc)
            time.sleep(3)
            continue
        if all(name in current for name in EXPECTED) and "Manually configured service" in current:
            failures = []
            for name, (group, expected) in EXPECTED.items():
                result = current[name]["results"][-1]
                if current[name].get("group") != group:
                    failures.append(f"{name}: group {current[name].get('group')!r}, expected {group!r}")
                if result["success"] != expected:
                    failures.append(f"{name}: success={result['success']} expected {expected}: "
                                    f"{result.get('conditionResults')} {result.get('errors')}")
            failures += [f"{name}: should not be monitored" for name in ABSENT if name in current]
            if failures:
                sys.stderr.write("FAIL\n" + "\n".join(failures) + "\n")
                return 1
            sys.stdout.write("OK: " + ", ".join(sorted(current)) + "\n")
            return 0
        last_error = f"endpoints so far: {sorted(current)}"
        time.sleep(3)
    sys.stderr.write(f"FAIL: timeout, {last_error}\n")
    return 1


if __name__ == "__main__":
    sys.exit(main())
